a = int(input("Enter number 1: "))

b = int(input("Enter number 2: "))

print("Number a is: ", a)
print("Number b is: ", b) 
print("Sum is ", a + b)
print("Difference is ", a - b)
print("Product is ", a * b)
print("Quotient is ", a / b)
print("Integer Division is ", a // b)
print("Remainder is ", a % b)
print("Power is ", a ** b)
print("a equals b: ", a == b)
print("a not equals b: ", a != b)
print("a greater than b: ", a > b)
print("a less than b: ", a < b)
print("a greater than or equals b: ", a >= b)
print("a less than or equals b: ", a <= b)